/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 piano.gltf 
Author: AEN (https://sketchfab.com/aenikl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/piano-6fdfd05ed18c4c8796f54b44e572e873
Title: Piano
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3D Models/piano/piano.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.84}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Piano_New_mat} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/piano.gltf')
